// <auto-generated />
using System;
using BookCatalogService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCatalogService.Infrastructure.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250329141948_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCatalogService.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Author")
                        .HasDatabaseName("IX_Books_Author");

                    b.HasIndex("Category")
                        .HasDatabaseName("IX_Books_Category");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Books_Title");

                    b.HasIndex("Title", "Author", "Category")
                        .HasDatabaseName("IX_Books_Title_Author_Category");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1182443b-6bc3-400e-a9f6-ff74631b4ee5"),
                            Author = "Robert C. Martin",
                            Category = 1,
                            Price = 19.99m,
                            PublishedAt = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 50,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("1d74449c-c3b9-4452-b08c-10bbe67decbc"),
                            Author = "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
                            Category = 1,
                            Price = 42.99m,
                            PublishedAt = new DateTime(1994, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 30,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = new Guid("4731710e-f850-41ea-b784-060990c98c0c"),
                            Author = "George R.R. Martin",
                            Category = 2,
                            Price = 29.99m,
                            PublishedAt = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 18,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("642f8f31-f836-4035-97c2-6c7e9aeef8dc"),
                            Author = "Gillian Flynn",
                            Category = 8,
                            Price = 14.99m,
                            PublishedAt = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 18,
                            Title = "Gone Girl"
                        },
                        new
                        {
                            Id = new Guid("67511f83-662a-4ec7-9d34-1e1ebec09b4c"),
                            Author = "",
                            Category = 8,
                            Price = 14.99m,
                            PublishedAt = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 18,
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = new Guid("6bb27932-6f2b-4353-a1b8-abbf34e06d96"),
                            Author = "Harper Lee",
                            Category = 13,
                            Price = 15.99m,
                            PublishedAt = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 20,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("83972487-6423-4d1b-8c76-2035646fba6d"),
                            Author = "F. Scott Fitzgerald",
                            Category = 13,
                            Price = 13.50m,
                            PublishedAt = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 25,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("e07821e7-309d-4c8e-b288-531332f59b8f"),
                            Author = "Fyodor Dostoevsky",
                            Category = 12,
                            Price = 17.99m,
                            PublishedAt = new DateTime(1866, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 5,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("ee7d491f-a0dc-4f55-b959-252db34de20f"),
                            Author = "Mario Puzo",
                            Category = 13,
                            Price = 21.99m,
                            PublishedAt = new DateTime(1969, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 15,
                            Title = "The Godfather"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
